### ISSUE TITLE
User error - please delete...

### ISSUE THREAD

**Issue by peteruhrig** [smarthomeNG/smarthome#197]
```
me@homeserver:/usr/local/smarthome/bin$ python3 ./smarthome.py -d > blalog.txt
[11/Feb/2017:20:16:27] ENGINE Bus STARTING
CherryPy Checker:
dir is an absolute path, even though a root is provided.
section: [/static]
root: '/data/familie/haussteuerung/smarthome/plugins/backend'
dir: '/data/familie/haussteuerung/smarthome/plugins/backend/static'

[11/Feb/2017:20:16:27] ENGINE Started monitor thread '_TimeoutMonitor'.
Exception in thread smartvisu:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/data/familie/haussteuerung/smarthome/lib/plugin.py", line 114, in run
    self.plugin.run()
  File "/data/familie/haussteuerung/smarthome/plugins/visu_smartvisu/__init__.py", line 81, in run
    svgen = SmartVisuGenerator(self._sh, self.smartvisu_dir, self.overwrite_templates, self.visu_style)
  File "/data/familie/haussteuerung/smarthome/plugins/visu_smartvisu/__init__.py", line 113, in __init__
    self.copy_templates()
  File "/data/familie/haussteuerung/smarthome/plugins/visu_smartvisu/__init__.py", line 375, in copy_templates
    shutil.copy2( srcdir + '/' + fn, self.tpldir )
  File "/usr/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Keine Berechtigung: '/var/www/html/smartVISU/pages/base/tplNG/room.html'
```

The latest 2.8 release of smartVISU has a /var/www/html/smartVISU/pages/base/tpl/ but not a /var/www/html/smartVISU/pages/base/tplNG/ directory.

**Comment by peteruhrig** [comment]
I am very sorry for this unnecessary issue. I now realize that smarthome-ng copies over the directory, but I accidentally started it under my own username, which lacks the rights to create the directory.
