### ISSUE TITLE
backend plugin: Edit/Save logic problem

### ISSUE THREAD

**Issue by ThomasCr** [smarthomeNG/smarthome#206]
Hi, today I wanted to edit a logic over the backend plugin, but when I push save and reload I get this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/smarthomeng-dev/plugins/backend/BackendCore.py", line 617, in logics_view_html
    self.process_logics_action(logic, trigger, reload, enable, savereload, logics_code, None, None, None)
  File "/usr/local/smarthomeng-dev/plugins/backend/BackendCore.py", line 657, in process_logics_action
    self.logic_save(logic, logics_code)
  File "/usr/local/smarthomeng-dev/plugins/backend/BackendCore.py", line 744, in logic_save
    f.write(logics_code)
TypeError: write() argument must be str, not bytes
```
Im at the current develop plugin branch.

**Comment by ThomasCr** [comment]
I updated now all python modules with "python3 -m pip install --upgrade $pkg" and restarted smarthome.py afterwards.
But the problem looks the same. But in addidtion, I dont get the file content in the edit box (and off cause - cant read/edit the file).

**Comment by ThomasCr** [comment]
ok, at least, I found, that the content of the problematic file has be deleted. maybe from the first problem.
But after update the python modules and at least restore the backup - the main problem is gone.
So I close the issue again.
