### ISSUE TITLE
Database plugin connection issue

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#231]
I just got this error on startup:
```
2017-09-14  22:54:41 ERROR    Main         Database [Database]: Could not connect to the database: (2003, "Can't connect to MySQL server on '10.0.0.100' (timed out)")
2017-09-14  22:54:41 ERROR    Main         Plugin database_nas exception: (2003, "Can't connect to MySQL server on '10.0.0.100' (timed out)")
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 916, in connect
    **kwargs)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/smarthome/lib/plugin.py", line 90, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance)
  File "/usr/local/smarthome/lib/plugin.py", line 144, in __init__
    exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthome/plugins/database/__init__.py", line 84, in __init__
    self._db.connect()
  File "/usr/local/smarthome/lib/db.py", line 192, in connect
    self._conn = self._dbapi.connect(**self._params)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 706, in __init__
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 963, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '10.0.0.100' (timed out)")
```
1) I think the error messages should be caught with a try / except
2) It would be great to have the plugin retry to connect after some time.

Additionally I got some "skip dump, already running" warnings. This happens quite often when the database is on the Pi itself, but even on a quite fast Synology NAS. Is there a chance to queue the dumps? Or is the warning not important anyhow?

**Comment by ohinckel** [comment]
> 1. I think the error messages should be caught with a try / except

When this error occurs the plugin will not work since it initially create the connection and setup/update the database structure. Without this the plugin can not work with the tables.

> 2. It would be great to have the plugin retry to connect after some time.

In all other place the plugin is retrying to connect to the database (you should get some log messages in this case). The mentioned exception is only a problem in the plugin startup (`__init__()` method).

Is it worth to implement some logic which will postpone the database connect and setup to the first database connect?

> Additionally I got some "skip dump, already running" warnings.

I'm also running SHNG on RPI with MySQL and do not have such problems (database is on connected HDD). When getting such messages it means that the dump just takes too long. How item updates are you doing? How large is your database?

**Comment by onkelandy** [comment]
I think a postponing could be useful just in case. Won't happen too often but as there is already a reconnect option why not using it at startup, too?

Weird that you don't have any problems with the Pi. SD card shouldn't be a problem but maybe logging, etc. is interfering? It was more or less useless for me on the Pi. Database was completely empty when testing it. Currently there are 240 items that are written to the DB.

**Comment by ohinckel** [comment]
Just commited a patch which moves the initialization of the database plugin to a later point. In case the database can not be connected on plugin startup it is now initialized when the plugin tries to access the database (e.g. when running the dump or querying data).

If you want you can review and check this patch before I create a PR for this.

**Comment by onkelandy** [comment]
Thanks. With your latest version I get this error at the beginning with no database running:
```
2018-05-10  23:10:00 ERROR    Database dump  Database [Database]: Could not connect to the database: (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-05-10  23:10:00 ERROR    Database dump  Database: initialization failed: (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-05-10  23:10:12 INFO     Main         Loading '/usr/local/smarthome/items/avm.yaml' to 'OrderedDict'
2018-05-10  23:10:13 ERROR    Main         Item env.core.memory: problem creating: 'NoneType' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/item.py", line 454, in __init__
    child = Item(smarthome, self, child_path, value)
  File "/usr/local/smarthome/lib/item.py", line 522, in __init__
    update = plugin.parse_item(self)
  File "/usr/local/smarthome/plugins/database/__init__.py", line 111, in parse_item
    cur = self._db.cursor()
  File "/usr/local/smarthome/lib/db.py", line 279, in cursor
    return self._conn.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
2018-05-10  23:10:18 ERROR    Main         Can not acquire lock for database to read value for item env.core.threads
2018-05-10  23:10:23 ERROR    Main         Can not acquire lock for database to read value for item env.core.garbage
2018-05-10  23:10:28 ERROR    Main         Can not acquire lock for database to read value for item env.system.load
```

Later on..
```
 23:15:01 WARNING  Database dump  Skipping dump, since other dump running!
```
what is not totally correct as there is no dump running but no connection. But even if the MYSQL server is running I still get this same error message - so no connect retry happening here :(?

**Comment by ohinckel** [comment]
When the database is not available on startup the item initialization based on database values can not be done (because of the missing database connection). This will be skipped now completely which fixes this error. So in case the database is not available at startup the `database = init` have no effect (items will be initialized with their defaults or cached value).

The message about a running dump it just because the exception handling did not removed the lock.
