### ISSUE TITLE
Problem with non-multiinstance but multi-class plugin  (mail)

### ISSUE THREAD

**Issue by 4d4mu** [smarthomeNG/smarthome#233]
In latest develop with mail plugin configured like in plugin readme, I get:

```
2017-09-18 19:41:04 DEBUG    plugin       Main         Plugins, section: mail -- plugin.py:__init__:79
2017-09-18 19:41:04 DEBUG    plugin       Main         Plugins __init__: pluginname = 'mail', classpath 'plugins.mail' -- plugin.py:_get_pluginname_and_metadata:130
2017-09-18 19:41:04 INFO     shyaml       Main         Loading '/home/smarthome/smarthome/plugins/mail/plugin.yaml' to 'OrderedDict' -- shyaml.py:yaml_load:80
2017-09-18 19:41:04 DEBUG    plugin       Main         PluginWrapper __init__: Section mail, classname SMTP, classpath plugins.mail -- plugin.py:__init__:297
2017-09-18 19:41:04 DEBUG    plugin       Main         Plugin 'SMTP': args = '{'password': "'xxx'", 'host': "'smtp.gmail.com'", 'username': "'xxx'", 'mail_from': "'xxx'", 'ssl': "'True'"}' -- plugin.py:__init__:335
2017-09-18 19:41:04 INFO     metadata     Main         Metadata plugin 'mail': No parameter definitions found in metadata -- metadata.py:check_parameters:495
2017-09-18 19:41:04 DEBUG    plugin       Main         Plugins: Loaded plugin 'mail' (class 'SMTP') v1.3.1: Integration von E-Mail-Accounts -- plugin.py:__init__:375
2017-09-18 19:41:04 INFO     plugin       Main         Initialized plugin 'mail' from from section 'mail' -- plugin.py:__init__:101
2017-09-18 19:41:04 DEBUG    plugin       Main         Plugins, section: imap -- plugin.py:__init__:79
2017-09-18 19:41:04 DEBUG    plugin       Main         Plugins __init__: pluginname = 'mail', classpath 'plugins.mail' -- plugin.py:_get_pluginname_and_metadata:130
2017-09-18 19:41:04 INFO     shyaml       Main         Loading '/home/smarthome/smarthome/plugins/mail/plugin.yaml' to 'OrderedDict' -- shyaml.py:yaml_load:80
2017-09-18 19:41:04 WARNING  plugin       Main         Plugin section 'imap' uses same class 'SMTP' and instance 'default' as plugin section 'mail' -- plugin.py:_test_duplicate_pluginconfiguration:221
2017-09-18 19:41:04 DEBUG    plugin       Main         PluginWrapper __init__: Section imap, classname SMTP, classpath plugins.mail -- plugin.py:__init__:297
2017-09-18 19:41:04 DEBUG    plugin       Main         Plugin 'SMTP': args = '{'host': "'imap.gmail.com'", 'username': "'xxx'", 'password': "'xxx'", 'ssl': "'True'"}' -- plugin.py:__init__:335
2017-09-18 19:41:04 INFO     metadata     Main         Metadata plugin 'mail': No parameter definitions found in metadata -- metadata.py:check_parameters:495
2017-09-18 19:41:04 ERROR    plugin       Main         Plugin 'mail' from section 'imap' exception: __init__() missing 1 required positional argument: 'mail_from' -- plugin.py:__init__:107
Traceback (most recent call last):
  File "/home/smarthome/smarthome/lib/plugin.py", line 95, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance, self.meta)
  File "/home/smarthome/smarthome/lib/plugin.py", line 354, in __init__
    exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
  File "<string>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'mail_from'

```

looks like smarthome is getting good params but wrong class: twice "SMTP" instead of "SMTP" and "IMAP". Part of plugin.yaml:

```
mail:
    class_name: SMTP
    class_path: plugins.mail
    host: smtp.gmail.com
    ssl: True


imap:
    class_name: IMAP
    class_path: plugins.mail
    host: imap.gmail.com
    ssl: True
```

Maybe it is connected with plugins/mail/plugin.yaml? Suspicious lines:
```
    classname: SMTP                # class containing the plugin
#    classname: IMAP                # class containing the plugin
```

**Comment by msinn** [comment]
Make a new pull of the core. I fixed the plugin Loader. Now a specified class_name in the /etc/plugin.yaml has precedence before the metadata definition.

This problem arose, because the mail plugin implements the mail support as two plugins in one file. It is the only plugin written that way. A new mail plugin should get rid of that kind of implementation and stick to the rule "one plugin directory -> one plugin".

**Comment by msinn** [comment]
Is it working ok now?

**Comment by 4d4mu** [comment]
yes, thanks!
