### ISSUE TITLE
Make SHNG OSX compatible

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#241]
This Issue is to track the changes to make SHNG OSX compatible. It builds up on the work already done by @tbrandstetter and on the actual develop branch.

**Comment by Foxi352** [comment]
Locales check on SHNG startup raises exceptions. Locales on standard untouched OSX installation (High Sierra) are:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

```

```
Traceback (most recent call last):
  File "bin/smarthome.py", line 968, in <module>
    if locale.getdefaultlocale() == (None, None):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 562, in getdefaultlocale
    return _parse_localename(localename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

Proposed mitigation is to change (smarthome.py line 968 - :
```
    if locale.getdefaultlocale() == (None, None):
        locale.setlocale(locale.LC_ALL, 'C')
    else:
        locale.setlocale(locale.LC_ALL, '')

```

to 

```
    try:
        if locale.getdefaultlocale() == (None, None):
            locale.setlocale(locale.LC_ALL, 'C')
        else:
            locale.setlocale(locale.LC_ALL, '')
    except:
        locale.setlocale(locale.LC_ALL, 'C')

```

This correctly sets the LC_ALL

**Comment by Foxi352** [comment]
UTF-8 locale test fails on OSX. Around line 253 of smarthome.py:

```
        # test if a valid locale is set in the operating system
        if os.environ['LANG'].find('UTF-8') == -1:
            self._logger.error("Locale for the enviroment is not set to a valid value. Set the LANG environment variable to a value supporting UTF-8")

```
fails with:
```
2017-11-01 14:58:58 ERROR    smarthome    Main         Unhandled exception: 'LANG'
<class 'KeyError'>
  File "bin/smarthome.py", line 1042, in <module>
    sh = SmartHome(extern_conf_dir=extern_conf_dir)
  File "bin/smarthome.py", line 253, in __init__
    if os.environ['LANG'].find('UTF-8') == -1:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
 -- smarthome.py:_excepthook:901

```
Possible mitigation, although not very clean IMHO:
```
        # test if a valid locale is set in the operating system
        try:
            if os.environ['LANG'].find('UTF-8') == -1:
                self._logger.error("Locale for the enviroment is not set to a valid value. Set the LANG environment variable to a value supporting UTF-8")
        except:
            self._logger.error("Locale for the enviroment is not set to a valid value. Set the LANG environment variable to a value supporting UTF-8")

```

**Comment by Foxi352** [comment]
Commit https://github.com/smarthomeNG/smarthome/commit/e56f89755b921dbac9c429725243ceb36a2708db modified check_sh_is_running function to be compatible with OSX.

**Comment by ohinckel** [comment]
Maybe you can check [the changes](https://github.com/smarthomeNG/smarthome/compare/develop...osx) from @tbrandstaetter for OSX compatibility, too. Hopefully there's something we can integrate now and remove the obsolete `osx` branch.

**Comment by Foxi352** [comment]
@ohinckel read my first comment on top 😉.That is the plan. I was able to use some of his paths, but some were no longer valid because of heavy code change meanwhile.
The only thing left is the connection lib. I will port his workarounds into the latest version of the connection lib for medium term use. The long term goal is to replace the connection lib with the new network lib under development.

I think this issue will be closed short term. Most code is already running...

**Comment by ohinckel** [comment]
OK, in this case we do not need the `osx` branch anymore. The implementation is going into the `develop` directly and we should delete the `osx` branch just to clean up things.

**Comment by Foxi352** [comment]
Yes, i will do it as soon as i have finished transposing everything usefull manually into devel. I'll take care of the osx branch.

**Comment by onkelandy** [comment]
Great to see Mac OSX compatibility getting implemented in the main branch!!
Right now I get the following errors when installing all requirements:
Double requirement given: python-dateutil>=2.5.3 (from -r requirements/all.txt (line 31)) (already in python-dateutil==2.5.3 (from -r requirements/all.txt (line 27)), name='python-dateutil')

Additionally psutil ans uptime are not being installed but needed. Maybe something to keep in mind, maybe it's just because the osx branch is not totally up to date..?

**Comment by Foxi352** [comment]
@onkelandy The osx branch is dead and i will remove it soon. It was way to much out of date to merge. I have manually implemented some changes to the current develop branch. Adding uptime to base.txt was one of them. But that was the only thin i touched concerning requirements.

Are you sure you are on the latest pull ? Because i have uptime in base.txt and since @msinn regenerated the all.txt i also see it there. So it should get installed.

When i do `pip3 install -r all.txt` i have no errors and everything is working. OSX and Linux.

**Comment by msinn** [comment]
Isn't it ready yet?

**Comment by Foxi352** [comment]
It is, but this is more a "continuous" ticket. From time to time i check the core (and some standard plugins like knx) if they still work on OSX. Sometimes small adaptations need to be done. I wanted a place to track all the work in this context. Same for IPv6. But i agree this is not really a single "issue". So if you don't want to keep them open we can close both issues and i will just do the commits with a comment without reference to an issue.

**Comment by msinn** [comment]
Since the name of the issue is **Make SHNG OSX compatible**, I think it shoud be closed when the goal is reached.

If a condtition arises in the future, that makes shNG OSX-incampatible, a new issue can/should be opened.

**Comment by onkelandy** [comment]
Just to add to the locale check issue.. This line 287 would be better.. My Synology has the locales set to utf8 (small letters)..

if os.environ['LANG'].lower().find('utf-8') == -1 and os.environ['LANG'].lower().find('utf8') == -1:

**Comment by Foxi352** [comment]
Sounds valid. I will test it on linux and osx before closing this issue.

**Comment by bmxp** [comment]
Maybe make it a bit more pythonic and use in instead of .find() (https://stackoverflow.com/questions/18437798/find-vs-in-operation-in-string-python)

**Comment by Foxi352** [comment]
The best i can come up with:

`if not 'utf-8' in os.environ['LANG'].lower() and not 'utf8' in os.environ['LANG'].lower():`

Isn't there something like `if not ('utf-8' or 'utf8') in os.environ['LANG'].lower() :` ?

If not i'll commit this one ...

**Comment by onkelandy** [comment]
This should also work:
if any(utf in os.environ['LANG'].lower() for utf in ['utf-8', 'utf8']):

**Comment by Foxi352** [comment]
Yeah if you add the `not` it seems to work. I will commit that one for testing (in devel of course)

**Comment by Foxi352** [comment]
@onkelandy Can you please test. If it works i'll close this issue.

**Comment by Foxi352** [comment]
I know, this was changed somewhen but i don't know why. I asked but did not get a response. I think they once removed all x flags from all .py files in purpose. So i don't dare to add it as long as no one states on this. But i agree, it sucks :-)
