### ISSUE TITLE
Database Plugin: Error handling when problems with database exist

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#302]
Momentan scheint bei meiner Datenbank etwas nicht zu passen. Die Tabellen können wohl nicht so abgefragt werden wie sie sollen. Das Problem an der Sache ist nun, dass das Database-Plugin diesen Fehler nicht sauber abfängt. Nach dem unten stehenden Error kommt smarthomeNG in einen sonderbaren Zustand:
Prinzipiell läuft es noch, allerdings ist es nicht möglich, sich per Visu oder CLI damit zu verbinden.

```
2018-12-27  11:18:52 ERROR    root              Can not execute query: INSERT INTO log(item_id, time, val_str, val_num, val_bool, duration, changed) VALUES (%(id)s,%(time)s,%(val_str)s,%(val_num)s,%(val_bool)s,%(duration)s,%(changed)s); (args OrderedDict([('id', 282), ('time', 1545905787920), ('val_str', None), ('val_num', 0.0), ('val_bool', 0), ('duration', 125856), ('changed', 1545905931530)])): (2013, 'Lost connection to MySQL server during query')
2018-12-27  11:18:52 WARNING  plugins.database  Database: Running query INSERT INTO log(item_id, time, val_str, val_num, val_bool, duration, changed) VALUES (282,1545905787920,None,0.0,0,125856,1545905931530);: (2013, 'Lost connection to MySQL server during query')
2018-12-27  11:18:52 ERROR    root              Can not execute query: SELECT time, item_id, duration, val_str, val_num, val_bool, changed FROM log WHERE item_id = %(id)s AND time = %(time)s; (args OrderedDict([('id', 282), ('time', 1545905913776)])): (0, '')
2018-12-27  11:18:52 WARNING  plugins.database  Database: Running query SELECT time, item_id, duration, val_str, val_num, val_bool, changed FROM log WHERE item_id = 282 AND time = 1545905913776;: (0, '')
2018-12-27  11:18:52 WARNING  plugins.database  Database: problem updating betriebsstunden.rme2c8: object of type 'NoneType' has no len()
2018-12-27  11:18:52 ERROR    Database dump nas_nas Method Database dump nas_nas exception: (0, '')
Traceback (most recent call last):
  File "/usr/local/smarthome/plugins/database/__init__.py", line 368, in _dump
    if len(self.readLog(id, t[0], cur)):
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 521, in _task
    obj()
  File "/usr/local/smarthome/plugins/database/__init__.py", line 381, in _dump
    self._db.rollback()
  File "/usr/local/smarthome/lib/db.py", line 275, in rollback
    self._conn.rollback()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 429, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 750, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
2018-12-27  11:19:54 WARNING  plugins.database  Skipping dump, since other dump running!
2018-12-27  11:20:59 WARNING  plugins.database  Skipping dump, since other dump running!
```

**Comment by ohinckel** [comment]
Der Fehler wird schon abgefangen. Allerdings wird im Fehlerfall versucht ein Rollback der Transaktion durchzuführen. Und das ging in diesem Fall ebenfalls schief, weil die Verbindung zum Datenbankserver geschlossen wurde (Lost connection to MySQL server).

Was man machen könnte wäre, die Exceptions während des Rollbacks zu fangen und zu ignorieren (Log schreiben, weiter nichts; vermutlich kann man in diesem Fall sowieso nicht mehr retten).

Damit könnte man zumindest für einen "sauberen" Zustand sorgen und ggf. wird dann beim nächsten Dump wieder versucht die Verbindung aufzumachen.

Warum es in deinem Fall zu diesem Fehler überhaupt kommt ist ein anderes Thema. Kann an Server-Einstellungen liegen, aber auch an der Client-Implementierung oder den -Einstellungen.

**Comment by onkelandy** [comment]
Ich glaube es gab ein Problem beim Restore eines Backups, aber das spielt eh keine Rolle. Cool wäre auf jeden Fall, wenn das irgendwie abgefangen werden könnte. Kann vermutlich auch in anderen Fällen mal so eintreten wie oben beschrieben.
Thx!

**Comment by ohinckel** [comment]
Exceptions werden nun an dieser Stelle abgefangen. Falls du das Problem rekonstruieren kannst, waere es gut, wenn man das kurz mal testen koennte.

**Comment by onkelandy** [comment]
Es sieht soweit gut aus. Im Log steht nun Folgendes:
```
2018-12-29  16:39:10 ERROR    root              Can not execute query: SELECT 1 (args OrderedDict()): (2013, 'Lost connection to MySQL server during query')
2018-12-29  16:39:10 WARNING  root              Database [Database]: Connection error (2013, 'Lost connection to MySQL server during query')
2018-12-29  16:39:15 ERROR    root              Database [Database]: Could not connect to the database: (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  16:39:15 WARNING  root              Database [Database]: Connection error (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  16:39:20 ERROR    root              Database [Database]: Could not connect to the database: (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  16:39:20 WARNING  root              Database [Database]: Connection error (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  16:39:25 ERROR    root              Database [Database]: Could not connect to the database: (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  16:39:25 WARNING  root              Database [Database]: Connection error (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  16:39:30 ERROR    root              Database [Database]: Could not connect to the database: (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  16:39:30 WARNING  root              Database [Database]: Connection error (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  16:39:30 ERROR    plugins.database  Database: Connection not recovered, skipping dump
2018-12-29  16:40:10 ERROR    root              Database [Database]: Could not connect to the database: (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  16:40:10 ERROR    plugins.database  Database: initialization failed: (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
```
wenn kein SQL Server verfügbar ist. Davor war das bei mir immer " Skipping dump, since other dump running!". Oder ist das Zufall?

**Comment by ohinckel** [comment]
Ursprünglich gab es eine Verbindung zur Datenbank. Während des Dumps ging die Verbindung verloren, wodurch eine Exception erzeugt wurde, die wiederum zum Rollback geführt hat. Und der Rollback ging dann auch nicht und der Zustand war dann fehlerhaft (keine weiteren Dumps, keine Anfragen mehr zu DB etc.).

Der Fix fängt nun diesen Fehler beim Rollback ab damit der Zustand wieder OK ist und das Plugin weiter funktioniert.

Deine Logs zeigen den initialen Verbindungsaufbau, den wir in https://github.com/smarthomeNG/plugins/pull/145 nun verzögert machen. D.h. es wird auch später nochmal versucht die Verbindung aufzubauen.

Später sieht man dann noch den Fehler während des Dumps, der aber auch wegen fehlender Verbindung schon gar nicht weiter versucht wird und übersprungen wird.

Beides hat also nichts mit der Änderung zu tun. Man müsste die Verbindung schon aufbauen lassen und erst später, z.B. durch Stoppen des DB-Servers, trennen. Bestenfalls während der Dump läuft.

**Comment by onkelandy** [comment]
Mal sehen, ob das mehr bringt ;) Hab nun beim Start eine Verbindung, die ich dann zwischendurch kappe und wiederherstelle. Mitten im dump..
```
2018-12-29  21:59:50 DEBUG    plugins.database  SELECT {log_columns} FROM {log} WHERE (item_id = :id                                      ) AND (time    = :time          OR 1 = :time_flag         ) AND (time    > :time_start    OR 1 = :time_start_flag   ) AND (time    < :time_end      OR 1 = :time_end_flag     ) AND (changed = :changed       OR 1 = :changed_flag      ) AND (changed > :changed_start OR 1 = :changed_start_flag) AND (changed < :changed_end   OR 1 = :changed_end_flag  );
2018-12-29  22:00:18 WARNING  plugins.database  Database: Running query SELECT time, item_id, duration, val_str, val_num, val_bool, changed FROM log WHERE (item_id = 9                                      ) AND (time    = None          OR 1 = 1         ) AND (time    > None    OR 1 = 1   ) AND (time    < None      OR 1 = 1     ) AND (changed = None       OR 1 = 1      ) AND (changed > None OR 1 = 1) AND (changed < None   OR 1 = 1  );    : (1053, 'Server shutdown in progress')
2018-12-29  22:00:18 DEBUG    plugins.database  Fetch SELECT time, item_id, duration, val_str, val_num, val_bool, changed FROM log WHERE (item_id = 9                                      ) AND (time    = None          OR 1 = 1         ) AND (time    > None    OR 1 = 1   ) AND (time    < None      OR 1 = 1     ) AND (changed = None       OR 1 = 1      ) AND (changed > None OR 1 = 1) AND (changed < None   OR 1 = 1  );    : None

2018-12-29  22:00:18 DEBUG    plugins.database  Starting dump
2018-12-29  22:00:18 DEBUG    plugins.database  Dump completed
2018-12-29  22:01:19 DEBUG    plugins.database  Starting dump
2018-12-29  22:01:19 DEBUG    plugins.database  Dump completed
2018-12-29  22:02:19 DEBUG    plugins.database  Starting dump
2018-12-29  22:02:19 DEBUG    plugins.database  Dump completed
```

Etwas irritierend ist das "Dump completed", obwohl keine Verbindung besteht. Ruf ich dann das Webinterface auf, kommt

```
2018-12-29  22:03:05 DEBUG    plugins.database  SELECT {item_columns} from {item} WHERE name = :id;
2018-12-29  22:03:19 DEBUG    plugins.database  Starting dump
2018-12-29  22:03:19 ERROR    plugins.database  Database: initialization failed: (2003, "Can't connect to MySQL server on '10.0.0.150' ([Errno 111] Verbindungsaufbau abgelehnt)")
2018-12-29  22:03:25 ERROR    plugins.database  Database: Connection not recovered
```

**Comment by ohinckel** [comment]
Dump completed wird immer am Ende gejoggt (kann sich sein, das einzelne Items erfolgreich gedumpt würden, andere aber nicht). Man könnte zählen, wieviel Items erfolgreich und wie viel nicht erfolgreich waren.

Die Logs haben nichts mit der Fehlerbehandlung zu tun. Entweder ist die Verbindung noch nicht aufgebaut gewesen (letzter Fehler) oder es kommt zu keiner Meldung (Starting dump ... Dump complete). Den richtigen Zeitpunkt während des Dumps zu treffen ist vermutlich nicht so einfach. Grade dann, wenn es nur wenig items zu finden gibt.

**Comment by onkelandy** [comment]
Ich hätte erwartet, dass beim Starting dump eine Meldung kommt, dass keine Verbindung hergestellt werden konnte. Sonst hat man das Gefühl, es passt eh alles. Weil zu dem Zeitpunkt (22:01) war der sql server down.

**Comment by ohinckel** [comment]
Wenn es keine Daten gibt, die gedumpt werden muessen, wird eine Verbindung zum Datenbankserver nicht benoetigt. Dann kommt auch keine Meldung.

**Comment by ohinckel** [comment]
Soeben habe ich eine Version gepusht, die die Exceptions nicht mehr abfaengt und ignoriert, sondern lediglich loggt und weiterwirf. Dadurch sollte erkennbar sein, wo es zum Haenger kommt bzw. wo es an anderen Stellen noch Probleme gibt.

**Comment by ohinckel** [comment]
Laesst sich das Problem noch genauer identifizieren oder koennen wir das Issue schliessen?

**Comment by onkelandy** [comment]
Ich habe nicht mehr groß versucht, das zu reproduzieren, denke aber, dass wir das schließen können. Zumal es ja ein paar Änderungen im Plugin dazu gab. Danke!
