### ISSUE TITLE
Mqtt plugin error

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#315]
Latest develop versions, all python modules up to date

As soon as the broker is not available there is this error:
```
019-05-04  22:40:18 ERROR    lib.plugin        Plugin 'mqtt' from section 'mqtt' exception: name 'ERROR' is not defined
Traceback (most recent call last):
  File "/usr/local/smarthome/plugins/mqtt/__init__.py", line 422, in ConnectToBroker
    self._client.connect(self.broker_ip, self.broker_port, 60)
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Keine Route zum Zielrechner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/smarthome/lib/plugin.py", line 145, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance, self.meta, self._gtrans)
  File "/usr/local/smarthome/lib/plugin.py", line 627, in __init__
    exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthome/plugins/mqtt/__init__.py", line 168, in __init__
    if not self.ConnectToBroker():
  File "/usr/local/smarthome/plugins/mqtt/__init__.py", line 423, in ConnectToBroker
    except ERROR as e:
NameError: name 'ERROR' is not defined
```

**Comment by msinn** [comment]
could you pull the mqtt plugin from the develop branch and have a look if the bug is fixed?

**Comment by onkelandy** [comment]
Looking good, thanks!
```
2019-05-05  20:57:46 ERROR    plugins.mqtt      Connection error: [Errno 113] Keine Route zum Zielrechner
2019-05-05  20:57:46 ERROR    lib.plugin        Plugins: Plugin 'mqtt' initialization failed, plugin not loaded
```
