### ISSUE TITLE
Handle referencing non-existent struct definitions.

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#319]
This is a cosmetic issue only so no hurry ;)

When you reference a struct that doesn't exist the error handling/catching isn't very nice at the moment. shng still tries to cast the missing struct to a specific type that is defined in the parent item, e.g.:
```
rules:
    type: bool
    struct: rules_heimkino_end
```

results in:
```
2019-05-30 09:50:03 CEST ERROR    lib.item            item                __init__     ln:722 Item licht.treppe.garderobe.automatik.rules: value ERROR: struct 'licht_rules_heimkino_end' not found! does not match type bool.  ----  Main         
2019-05-30 09:50:03 CEST ERROR    lib.item            item                __init__     ln:685 Item licht.treppe.garderobe.automatik.rules: problem creating:   ----  Main         
Traceback (most recent call last):
  File "/Users/ank/smarthome/lib/item.py", line 683, in __init__
    child = Item(smarthome, self, child_path, value)
  File "/Users/ank/smarthome/lib/item.py", line 720, in __init__
    self._value = self.cast(self._value)
  File "/Users/ank/smarthome/lib/item.py", line 2446, in _cast_bool
    raise ValueError
ValueError
```

**Comment by bmxp** [comment]
@onkelandy What about a PR with a more beautiful solution?

**Comment by msinn** [comment]
@onkelandy Should be fixed now

**Comment by onkelandy** [comment]
tested it successfully. thanks.
