### ISSUE TITLE
fade destination is automatically being casted to float

### ISSUE THREAD

**Issue by maddinador** [smarthomeNG/smarthome#332]
I was playing around with a logic for a KNX dimmer switch (DPT3) and the artnet plugin sending values to my DMX bus.

logic watching items `*.dimming`:
```python
source_item = sh.return_item(trigger['source'])
[dim_direction, dim_active] = trigger['value']

if dim_active:
        target_value = 255 if dim_direction else 0 # dim dir is being delivered by DPT3 item
        source_item.return_parent().dmx.fade(target_value, 16, 0.3) # target value, step, time
else: # stop fader by setting explicit value DIFFERENT from current value
        value = int(source_item.return_parent().dmx())
        if value >= 255:
                source_item.return_parent().dmx(254)
        else:
                source_item.return_parent().dmx(value + 1)
        source_item.return_parent().dmx(value)
```

item:
```yaml
Light:
        dmx:
                type: num
                artnet_address@eg: 30
                on_update: 
                    - logger.warning(value)
                    - sh.knx.groupwrite('0/2/13', int(value/255*100), '5.001')
        switch:
                type: bool
                knx_dpt: 1
                knx_listen: 0/0/13
                on_update: ..dmx = 255 if value else 0
                visu_acl: rw
        dimming:
                type: list
                knx_dpt: 3
                knx_listen: 0/1/0
```

I stumbled across this type conversion in `fade(...)`:
https://github.com/smarthomeNG/smarthome/blob/1dcb4fb5195f04eb00d129b59087ab85f163dcf8/lib/item.py#L2311

What happens when we reach `dest` while running a `_fadejob` is:
```
2019-09-08  07:02:37 WARNING  lib.item            207
2019-09-08  07:02:41 WARNING  lib.item            223
2019-09-08  07:02:41 WARNING  lib.item            239
2019-09-08  07:02:42 WARNING  lib.item            255.0
2019-09-08  07:02:42 ERROR    lib.item            Item Light.dmx: problem running <bound method ArtNet.update_item of <plugins.artnet.ArtNet object at 0x71362d30>>: required argument is not an integer
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/item.py", line 2224, in __update
    method(self, caller, source, dest)
  File "/usr/local/smarthome/plugins/artnet/__init__.py", line 162, in update_item
    self.send_single_value(adr, item())
  File "/usr/local/smarthome/plugins/artnet/__init__.py", line 220, in send_single_value
    self.__ArtDMX_broadcast()
  File "/usr/local/smarthome/plugins/artnet/__init__.py", line 264, in __ArtDMX_broadcast
    data.append(struct.pack('B', d))
struct.error: required argument is not an integer
```

The shown error occurs because `fade` is setting `value` to `dest` at the end of the fade job which is right in my opinion.
But `dest` had been casted to `float`...

Commenting it out helps in my case.

Does anyone know why this cast happens?

**Comment by msinn** [comment]
This cast ist probably there to ensure, that dest is a numeric value (in SmartHomeNG the parameter could have been handed over to the method as a string).

Why dest is casted to a float and not to an integer, I cannot say. This casting is part of the ancient code of the original smarthome.py (and I have never used fading).

**Comment by msinn** [comment]
I don't know which side effects the commenting out in item.py has. I would suggest to change the artnet plugin. Add a in conversion to line 264:

`data.append(struct.pack('B', int(d)))`

**Comment by bmxp** [comment]
@maddinador Did the suggestion from @msinn solve your problem?

**Comment by bmxp** [comment]
I've applied the fix @msinn suggested.
