### ISSUE TITLE
CherryPy preventing smarthomeNG from startup without network

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#341]
Hi!
I'm a fan of running smarthomeNG offline now and then (developing and testing in train, etc.). This is currently with the latest develop not possible as I get this error on startup:
```
2020-02-11  18:10:23 ERROR    cherrypy.error    [11/Feb/2020:18:10:23] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x10b9fcc88>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/servers.py", line 177, in start
    portend.free(*self.bind_addr, timeout=Timeouts.free)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/portend.py", line 123, in free
    raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout: Port 8384 not free on 127.0.0.1.

2020-02-11  18:10:23 ERROR    cherrypy.error    [11/Feb/2020:18:10:23] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 8384 not free on 127.0.0.1.',)
```

I might have a look at it myself but maybe someone else is quicker in fixing it. Main issue is that smarthome just won't start without a network connection

**Comment by msinn** [comment]
Does it work on v1.6 master with the same configuration?

**Comment by onkelandy** [comment]
Hm, this is weird. Suddenly there is no issue anymore. Yesterday it was pretty obvious and consistent :(
Nothing is running on 8384 except smarthome. 
I guess the above exception can't be catched anyhow? Hmmm, I'll keep on trying to reproduce my issue and close it if it was just a weird combination of mysterious events.

**Comment by msinn** [comment]
It has to be reproducable to be catched by smarthomheng, since it is (as your can see) already catched inside of cherrypy with the reaction **raise exception**.

**Comment by bmxp** [comment]
Are you sure there was no other instance of SHNG already running?

**Comment by msinn** [comment]
I reproduced exactly the same error(s): **Port 8384 not free** 
I added a check to the http module if the ports are already in use before initializing Cherrypy. 

(The exceptions raised by cherrypy cannot be captured by putting the startup call to a try/except clause)

**Comment by msinn** [comment]
@onkelandy cloud we close this issue?

**Comment by onkelandy** [comment]
Let's close it for now. If I can reproduce it somehow I'll reopen it ;)
