### ISSUE TITLE
Installing Core Requirements on fresh Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by mode2k** [smarthomeNG/smarthome#354]
First start:
```
smarthome@tulpe:/usr/local/smarthome$ python3 bin/smarthome.py

test_requirements: 'ephem' not installed. Minimum v3.7 needed
test_requirements: 'holidays' not installed. Minimum v0.9.11 needed
test_requirements: 'psutil' not installed, any version needed
test_requirements: 'ruamel.yaml' not installed. Minimum v0.15.0 needed

Installing core requirements for the current user, please wait...

len(stderr)=1371
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hch8_fqr/ruamel.yaml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hch8_fqr/ruamel.yaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o4u903ez
         cwd: /tmp/pip-install-hch8_fqr/ruamel.yaml/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hch8_fqr/ruamel.yaml/setup.py", line 211, in <module>
        pkg_data = _package_data(__file__.replace('setup.py', '__init__.py'))
      File "/tmp/pip-install-hch8_fqr/ruamel.yaml/setup.py", line 184, in _package_data
        data = literal_eval("".join(lines))
      File "/tmp/pip-install-hch8_fqr/ruamel.yaml/setup.py", line 156, in literal_eval
        return _convert(node_or_string)
      File "/tmp/pip-install-hch8_fqr/ruamel.yaml/setup.py", line 95, in _convert
        if isinstance(node, Str):
    NameError: name 'Str' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


Python package requirements not met - SmartHomeNG is terminating
ERROR: Unable to install core requirements

```

Installing the requirements manually also fails:
```
smarthome@tulpe:/usr/local/smarthome$ pip3 install -r requirements/base.txt --user
Ignoring ruamel.yaml: markers 'python_version < "3.7"' don't match your environment
Collecting cherrypy>=8.1.2
  Downloading CherryPy-18.6.0-py2.py3-none-any.whl (419 kB)
     |████████████████████████████████| 419 kB 1.4 MB/s
Collecting ephem>=3.7
  Using cached ephem-3.7.7.1-cp38-cp38-manylinux2010_x86_64.whl (1.2 MB)
Collecting holidays>=0.9.11
  Using cached holidays-0.10.2.tar.gz (110 kB)
Collecting jinja2>=2.9
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 26.1 MB/s
Collecting paho-mqtt>=1.2.2
  Downloading paho-mqtt-1.5.0.tar.gz (99 kB)
     |████████████████████████████████| 99 kB 21.0 MB/s
Collecting psutil
  Using cached psutil-5.7.0.tar.gz (449 kB)
Requirement already satisfied: pyjwt>=1.6.4 in /usr/lib/python3/dist-packages (from -r requirements/base.txt (line 32)) (1.7.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/lib/python3/dist-packages (from -r requirements/base.txt (line 35)) (2.7.3)
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from -r requirements/base.txt (line 38)) (2.22.0)
Collecting ruamel.yaml<=0.15.74,>=0.15.0
  Using cached ruamel.yaml-0.15.74.tar.gz (310 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p8mzvxwi/ruamel.yaml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p8mzvxwi/ruamel.yaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lfjssgbc
         cwd: /tmp/pip-install-p8mzvxwi/ruamel.yaml/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p8mzvxwi/ruamel.yaml/setup.py", line 211, in <module>
        pkg_data = _package_data(__file__.replace('setup.py', '__init__.py'))
      File "/tmp/pip-install-p8mzvxwi/ruamel.yaml/setup.py", line 184, in _package_data
        data = literal_eval("".join(lines))
      File "/tmp/pip-install-p8mzvxwi/ruamel.yaml/setup.py", line 156, in literal_eval
        return _convert(node_or_string)
      File "/tmp/pip-install-p8mzvxwi/ruamel.yaml/setup.py", line 95, in _convert
        if isinstance(node, Str):
    NameError: name 'Str' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This error occours with the latest git master version on ubuntu 20.04. Python Version is 3.8.2

**Comment by mode2k** [comment]
Found the issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1714177
But it should be solved in Version python-ruamel-yaml-0.15.41-6.fc32  but for me it does not work with version 0.15.74

**Comment by mode2k** [comment]
This Diff worked for me:
```
diff --git a/lib/requirements.txt b/lib/requirements.txt
index 7a3258af..11c01484 100644
--- a/lib/requirements.txt
+++ b/lib/requirements.txt
@@ -10,7 +10,7 @@ psutil

 # lib.shyaml:
 ruamel.yaml>=0.13.7,<=0.15.74;python_version<'3.7'
-ruamel.yaml>=0.15.0,<=0.15.74;python_version>='3.7'
+ruamel.yaml>=0.15.0,<=0.15.78;python_version>='3.7'
```

**Comment by onkelandy** [comment]
This is currenty working well, so I think this issue can be closed:
ruamel.yaml>=0.15.78,<=0.16.8;python_version>='3.8'
