### ISSUE TITLE
Backup from commandline not working

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#388]
Procedure as described here https://www.smarthomeng.de/user/konfiguration/konfiguration_backup_restore.html doesn't work.
```
bin/smarthome.py -cbt
Traceback (most recent call last):
  File "bin/smarthome.py", line 256, in <module>
    fn = lib.backup.create_backup(extern_conf_dir, BASE, filename_with_timestamp=True)
  File "/Users/ank/smarthome_testing/lib/backup.py", line 152, in create_backup
    now = shtime.now()
AttributeError: 'NoneType' object has no attribute 'now'
```

**Comment by msinn** [comment]
Is fixed in develop

**Comment by msinn** [comment]
Resolution went into master with release v1.8.2
