### ISSUE TITLE
websocket module excpetions

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#441]
```
Mai 09 04:12:08 ERROR    modules.websocket update_item - Error in 'await websocket.send(data)': code = 1001 (going away), no reason
Traceback (most recent call last):
  File "/usr/local/smarthome/modules/websocket/__init__.py", line 920, in update_item
    await websocket.send(msg)
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 471, in send
    await self.ensure_open()
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason
Mai 09 04:12:08 ERROR    modules.websocket update_item - Error in 'await websocket.send(data)': code = 1001 (going away), no reason
Traceback (most recent call last):
  File "/usr/local/smarthome/modules/websocket/__init__.py", line 920, in update_item
    await websocket.send(msg)
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 471, in send
    await self.ensure_open()
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason
Mai 09 04:12:08 ERROR    modules.websocket update_item - Error in 'await websocket.send(data)': code = 1001 (going away), no reason
Traceback (most recent call last):
  File "/usr/local/smarthome/modules/websocket/__init__.py", line 920, in update_item
    await websocket.send(msg)
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 471, in send
    await self.ensure_open()
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason
Mai 09 04:12:08 ERROR    modules.websocket update_item - Error in 'await websocket.send(data)': code = 1001 (going away), no reason
Traceback (most recent call last):
  File "/usr/local/smarthome/modules/websocket/__init__.py", line 920, in update_item
    await websocket.send(msg)
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 471, in send
    await self.ensure_open()
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason
Mai 09 04:12:08 ERROR    modules.websocket update_item - Error in 'await websocket.send(data)': code = 1001 (going away), no reason
Traceback (most recent call last):
  File "/usr/local/smarthome/modules/websocket/__init__.py", line 920, in update_item
    await websocket.send(msg)
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 471, in send
    await self.ensure_open()
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason
Mai 09 04:12:08 ERROR    modules.websocket update_item - Error in 'await websocket.send(data)': code = 1001 (going away), no reason
Traceback (most recent call last):
  File "/usr/local/smarthome/modules/websocket/__init__.py", line 920, in update_item
    await websocket.send(msg)
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 471, in send
    await self.ensure_open()
  File "/home/smarthome/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason
Mai 09 04:12:12 WARNING  modules.websocket Series cancelation: No series for path bewegung.aussen.terrasse_og.fuenf found in list
Mai 09 04:12:12 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series_cancel", "error": "No series for path bewegung.aussen.terrasse_og.fuenf found in list"}
Mai 09 04:12:12 WARNING  modules.websocket Series cancelation: No series for path bewegung.og.fuenf found in list
Mai 09 04:12:12 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series_cancel", "error": "No series for path bewegung.og.fuenf found in list"}
Mai 09 04:12:12 WARNING  modules.websocket Series cancelation: No series for path bewegung.og.kueche.fuenf found in list
Mai 09 04:12:12 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series_cancel", "error": "No series for path bewegung.og.kueche.fuenf found in list"}
Mai 09 04:12:12 WARNING  modules.websocket Series cancelation: No series for path bewegung.og.abgang.fuenf found in list
Mai 09 04:12:12 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series_cancel", "error": "No series for path bewegung.og.abgang.fuenf found in list"}
Mai 09 04:12:12 WARNING  modules.websocket Series cancelation: No series for path bewegung.og.wc.fuenf found in list
Mai 09 04:12:13 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series_cancel", "error": "No series for path bewegung.og.wc.fuenf found in list"}
Mai 09 04:12:13 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "item", "items": [["bewegung.eg.zeitstatus", 30], ["bewegung.eg.gang.zeitstatus", 30], ["bewegung.eg.bad.zeitstatus", 0], ["bett.belegung", 2], ["bett.andy", false], ["bett.andy.sperren", false], ["bett.riki", true], ["bett.riki.sperren", false], ["bwm.eg.bad.nachlaufzeit_aktiv", false], ["bwm.eg.bad.nachlaufzeit_aktiv.start.unix_timestamp", 0], ["bwm.eg.bad.nachlaufzeit.duration_format", "0h 5i 0s"], ["wetterstation.helligkeit.osten", 1.0], ["bwm.eg.bad.helligkeitstrigger", true], ["bwm.eg.bad.helligkeitsschwelle", 8000], ["bwm.eg.bad.nachlaufzeit", 5], ["bwm.eg.bad.sperren", false], ["bwm.eg.bad.visu_mastertrigger", false], ["bwm.eg.bad.visu_trigger", false], ["bwm.eg.bad.austrigger", false], ["bwm.eg.gang.nachlaufzeit_aktiv", false], ["bwm.eg.gang.nachlaufzeit_aktiv.start.unix_timestamp", 0], ["bwm.eg.gang.nachlaufzeit.duration_format", "0h 0i 0s"], ["bwm.eg.gang.helligkeitswert", 0.0], ["bwm.eg.gang.helligkeitstrigger", true], ["bwm.eg.gang.helligkeitsschwelle", 0.0], ["bwm.eg.gang.nachlaufzeit", 0], ["bwm.eg.gang.reichweite", 0], ["bwm.eg.gang.sperren", false], ["bwm.eg.gang.visu_mastertrigger", false], ["bwm.eg.gang.visu_trigger", false], ["bwm.eg.gang.immerdunkel", false], ["bwm.eg.bad.automatik.settings.nacht.helligkeitsschwelle", 8000], ["bwm.eg.bad.automatik.settings.standard.helligkeitsschwelle", 8900], ["bwm.eg.bad.automatik.settings.nacht.nachlaufzeit", 5], ["bwm.eg.bad.automatik.settings.standard.nachlaufzeit", 14]]}
Mai 09 04:12:13 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series", "series": [[1620439933058, 0.0], [1620449671282, 1.0], [1620450116880, 0.0], [1620454444378, 1.0], [1620456015003, 0.0], [1620456130745, 1.0], [1620456853330, 0.0], [1620456983935, 1.0], [1620457420163, 0.0], [1620458409284, 1.0], [1620458718198, 0.0], [1620458879584, 1.0], [1620459755501, 0.0], [1620459769008, 1.0], [1620460376303, 0.0], [1620466487010, 1.0], [1620466859127, 0.0], [1620467550240, 1.0], [1620467978769, 0.0], [1620471740312, 1.0], [1620472109984, 0.0], [1620477198716, 1.0], [1620477670798, 0.0], [1620479275388, 1.0], [1620479596804, 0.0], [1620483100100, 1.0], [1620484003455, 0.0], [1620491116347, 1.0], [1620491583346, 0.0], [1620491921600, 1.0], [1620492230796, 0.0], [1620501201890, 1.0], [1620501529600, 0.0], [1620501579021, 1.0], [1620501906024, 0.0], [1620502552805, 1.0], [1620503000972, 0.0], [1620520522084, 1.0], [1620520939021, 0.0], [1620520939021, 0.0], [1620526333058, 0.0]], "sid": "bewegung.eg.bad.fuenf|raw|24h|now|500"}
Mai 09 04:12:13 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series", "series": [[1620439933190, 0.0], [1620446416919, 1.0], [1620446720612, 0.0], [1620448476570, 1.0], [1620448942183, 0.0], [1620449479227, 1.0], [1620450131410, 0.0], [1620450530216, 1.0], [1620450846399, 0.0], [1620452913628, 1.0], [1620453274260, 0.0], [1620454321146, 1.0], [1620454997087, 0.0], [1620455395505, 1.0], [1620457442185, 0.0], [1620457467085, 1.0], [1620457878361, 0.0], [1620458328348, 1.0], [1620460569763, 0.0], [1620464555459, 1.0], [1620464894145, 0.0], [1620466152520, 1.0], [1620466870048, 0.0], [1620467285642, 1.0], [1620467976715, 0.0], [1620471380059, 1.0], [1620472167614, 0.0], [1620472321784, 1.0], [1620472629868, 0.0], [1620476252277, 1.0], [1620476609856, 0.0], [1620477193369, 1.0], [1620477669298, 0.0], [1620477690675, 1.0], [1620478217298, 0.0], [1620478439018, 1.0], [1620478747380, 0.0], [1620479274982, 1.0], [1620479593779, 0.0], [1620483099348, 1.0], [1620483440913, 0.0], [1620483596799, 1.0], [1620483998918, 0.0], [1620484573454, 1.0], [1620484905238, 0.0], [1620485337551, 1.0], [1620485869076, 0.0], [1620487664216, 1.0], [1620487967625, 0.0], [1620488321128, 1.0], [1620488639830, 0.0], [1620491066316, 1.0], [1620491581318, 0.0], [1620491915046, 1.0], [1620492254338, 0.0], [1620492351104, 1.0], [1620492688020, 0.0], [1620499030601, 1.0], [1620499374663, 0.0], [1620501012284, 1.0], [1620501523059, 0.0], [1620501579224, 1.0], [1620501901502, 0.0], [1620502550825, 1.0], [1620502996433, 0.0], [1620520519873, 1.0], [1620520938494, 0.0], [1620525249642, 1.0], [1620525557644, 0.0], [1620525557644, 0.0], [1620526333190, 0.0]], "sid": "bewegung.eg.gang.fuenf|raw|24h|now|500"}
Mai 09 04:12:13 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series", "series": [[1620439933284, 1.0], [1620450866466, 0.0], [1620450938213, 1.0], [1620451769914, 0.0], [1620455426829, 1.0], [1620455531597, 0.0], [1620455845531, 1.0], [1620455870135, 0.0], [1620455881585, 1.0], [1620455962338, 0.0], [1620501656392, 1.0], [1620501704507, 0.0], [1620501722001, 1.0], [1620502545773, 0.0], [1620502709684, 1.0], [1620520511288, 0.0], [1620520654737, 1.0], [1620520673813, 0.0], [1620520682774, 1.0], [1620520694819, 0.0], [1620520702345, 1.0], [1620525241818, 0.0], [1620525241818, 0.0], [1620526333284, 0.0]], "sid": "bett.andy|raw|24h|now|500"}
Mai 09 04:12:13 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series", "series": [[1620439933379, 1.0], [1620446391842, 0.0], [1620446400375, 1.0], [1620446404638, 0.0], [1620446423208, 1.0], [1620448861380, 0.0], [1620448888003, 1.0], [1620448999306, 0.0], [1620449633475, 1.0], [1620449656495, 0.0], [1620455451923, 1.0], [1620455531096, 0.0], [1620455560221, 1.0], [1620455761764, 0.0], [1620455854072, 1.0], [1620455868624, 0.0], [1620455882083, 1.0], [1620455960833, 0.0], [1620459313273, 1.0], [1620459336365, 0.0], [1620472349602, 1.0], [1620481683619, 0.0], [1620481692652, 1.0], [1620482581636, 0.0], [1620482589659, 1.0], [1620497860621, 0.0], [1620498337063, 1.0], [1620499619353, 0.0], [1620501608708, 1.0], [1620501608708, 1.0], [1620526333380, 1.0]], "sid": "bett.riki|raw|24h|now|500"}
Mai 09 04:12:13 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series", "series": [[1620483133468, 1.0], [1620484219007, 0.0], [1620484316119, 1.0], [1620484910762, 0.0], [1620485322755, 1.0], [1620485869072, 0.0], [1620487663185, 1.0], [1620487995167, 0.0], [1620488303945, 1.0], [1620488642292, 0.0], [1620491059724, 1.0], [1620491583341, 0.0], [1620491915138, 1.0], [1620492254338, 0.0], [1620492351159, 1.0], [1620492688524, 0.0], [1620499023721, 1.0], [1620499382125, 0.0], [1620501009812, 1.0], [1620501529595, 0.0], [1620501579168, 1.0], [1620501906037, 0.0], [1620502550929, 1.0], [1620503000967, 0.0], [1620520519992, 1.0], [1620520939010, 0.0], [1620525249761, 1.0], [1620525557648, 0.0], [1620525557648, 0.0], [1620526333468, 0.0]], "sid": "bewegung.eg.fuenf|max|12h|now|5000"}
Mai 09 04:12:13 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series", "series": [[1620483133562, 1.0], [1620483440913, 0.0], [1620483596799, 1.0], [1620483998918, 0.0], [1620484573454, 1.0], [1620484905238, 0.0], [1620485337551, 1.0], [1620485869076, 0.0], [1620487664216, 1.0], [1620487967625, 0.0], [1620488321128, 1.0], [1620488639830, 0.0], [1620491066316, 1.0], [1620491581318, 0.0], [1620491915046, 1.0], [1620492254338, 0.0], [1620492351104, 1.0], [1620492688020, 0.0], [1620499030601, 1.0], [1620499374663, 0.0], [1620501012284, 1.0], [1620501523059, 0.0], [1620501579224, 1.0], [1620501901502, 0.0], [1620502550825, 1.0], [1620502996433, 0.0], [1620520519873, 1.0], [1620520938494, 0.0], [1620525249642, 1.0], [1620525557644, 0.0], [1620525557644, 0.0], [1620526333562, 0.0]], "sid": "bewegung.eg.gang.fuenf|max|12h|now|5000"}
Mai 09 04:12:13 WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': code = 1001 (going away), no reason - reply = {"cmd": "series", "series": [[1620483133648, 1.0], [1620484003455, 0.0], [1620491116347, 1.0], [1620491583346, 0.0], [1620491921600, 1.0], [1620492230796, 0.0], [1620501201890, 1.0], [1620501529600, 0.0], [1620501579021, 1.0], [1620501906024, 0.0], [1620502552805, 1.0], [1620503000972, 0.0], [1620520522084, 1.0], [1620520939021, 0.0], [1620520939021, 0.0], [1620526333648, 0.0]], "sid": "bewegung.eg.bad.fuenf|max|12h|now|5000"}
```

Came "out of the blue". The exceptions happened just once so far but I guess could be catched easily. The "no series for path.." happens quite often, still not sure why

**Comment by msinn** [comment]
Original Issue: [plugins/#512](https://github.com/smarthomeNG/plugins/issues/512)

**Comment by onkelandy** [comment]
Meanwhile I still get quite some warnings. I guess they come from the Admin IF although I have never activated the graph page with the system resources. Not an exception thrown but still not optimal..
```
      1 Jan 02 11:00:37  WARNING  modules.websocket smartVISU_protocol_v4: Exception in 'await websocket.send(reply)': received 1005 (no status code [internal]); then sent 1005 (no status code [internal]) - reply = {"cmd": "series", "series": [[1641031237541, 8.99], .. lots of lists .. [1641117637541, 8.98]], "sid": "env.system.diskusagepercent|avg|24h|now|100"}
      ```

**Comment by onkelandy** [comment]
Not sure if this is module.websocket related but it's an exception out of the blue (no shng restart or such)
```
Jan 01 13:15:13 ERROR    websockets.server closing handshake failed
Traceback (most recent call last):
  File "/home/smarthome/.local/lib/python3.9/site-packages/websockets/legacy/server.py", line 239, in handler
    await self.close()
  File "/home/smarthome/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 779, in close
    await asyncio.shield(self.close_connection_task)
  File "/home/smarthome/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
    self.transport.write_eof()
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 972, in write_eof
    self._sock.shutdown(socket.SHUT_WR)
OSError: [Errno 107] Der Socket ist nicht verbunden
Jan 01 13:20:03 ERROR    modules.websocket smartVISU_protocol_v4 exception: no close frame received or sent
Jan 01 13:21:04 ERROR    modules.websocket smartVISU_protocol_v4 exception: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
Jan 01 13:41:03 ERROR    modules.websocket smartVISU_protocol_v4 exception: no close frame received or sent
```

**Comment by msinn** [comment]
This one originated while SmartHomeNG was shutting down. The Websocket module tried to close the the websocket connection by doing a closing handshake. This try failed, because the websocket connection was closed (by the browser without sending a propper "close connection") since the last server handshake.

Ok, this is an abnormal termination of the connection, but it should not be logged as an exception, because nothing really bad has happend.

**Comment by msinn** [comment]
Do you have any way to reproduce it? I cannot find if/where it originated from the websocket module.

**Comment by msinn** [comment]
Do you have any way to reproduce it? 

With the modifications to the websocket module in the last days: Does it still happen?

**Comment by onkelandy** [comment]
To be honest I couldn't reproduce that issue and I'm not sure where it originated from. Currently I only get these issues
```
Feb 22 19:59:50 WARNING  modules.websocket smartVISU_protocol_v4 error: Client localhost (127.0.0.1:58880), smartVISU v3.3.b, Safari 16 - sent 1011 (unexpected error) keepalive ping timeout; no close frame received
Feb 22 19:59:50 WARNING  modules.websocket smartVISU_protocol_v4 error: Client localhost (127.0.0.1:58880), smartVISU v3.3.b, Safari 16 - sent 1011 (unexpected error) keepalive ping timeout; no close frame received
Feb 22 20:07:56 WARNING  modules.websocket smartVISU_protocol_v4 error: Client localhost (127.0.0.1:45548), smartVISU v3.3.b, Safari 16 - no close frame received or sent
Feb 22 20:07:56 WARNING  modules.websocket smartVISU_protocol_v4 error: Client localhost (127.0.0.1:45548), smartVISU v3.3.b, Safari 16 - no close frame received or sent
```
not sure if ithere's really an issue or the warning somehow can be ignored..

**Comment by msinn** [comment]
Welche Version von pywebsockets hast Du installiert? Leider haben sich zwischen den Versionen die Texte der geworfenen Exceptions geändert…

**Comment by msinn** [comment]
Kannst Du auch die Version des websocket Moduls bei Dir nennen?

**Comment by onkelandy** [comment]
Muss ich versuchen nachzustellen.. mir ist auch nicht ganz klar, wann das auftritt. Konnte jetzt jedenfalls problemlos einen Tab mit Serienplot in der Visu öffnen und schließen. Ich glaub, beim Admin Interface gab's den Fehler auch, also nicht nur mit smartvisu. Aktuell nicht ad hoc reproduzierbar. Was mir aber grad auffällt, im Admin IF bleiben die Ressource Graphen ziemlich oft leer. Refresh und abwarten klappt dann aber für gewöhnlich.

pywebsockets: 10.4
websocket modul: 1.0.5

Hab das Modul jetzt mal auf 1.0.9 aktualisiert und beobachte nochmals...

**Comment by msinn** [comment]
Das ist die Version, die auch im master vorhanden ist. Teste bitte mit der Version aus dem develop. Dort ist die Version 1.0.9.

**Comment by msinn** [comment]
SmartHomeNG v1.9.4 has been released
