### ISSUE TITLE
lib.network: Invalid self.name check in __init__

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#487]
Pushover plugin is no longer working after lib.network commit [db62a3fcc6fd81026d8b496a8026d505d37ce4ce](https://github.com/smarthomeNG/smarthome/commit/db62a3fcc6fd81026d8b496a8026d505d37ce4ce).
Maybe other plugins are also affected ?

In lib.network Http class.__init__ the check `{self.name if self.name else "HTTP"}` is invalid. `Name` is a parameter to init and not an instance property, so probably `self._id = f'({name if name else "HTTP"}_{self.baseurl})'` is what was meant here ?

```
2022-03-28  19:45:01 ERROR    lib.plugin        Plugin 'pushover' from section 'po' exception: 'Http' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/plugin.py", line 162, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance, self.meta, self._configfile)
  File "/usr/local/smarthome/lib/plugin.py", line 629, in __init__
    exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthome/plugins/pushover/__init__.py", line 44, in __init__
    self._po = Http()
  File "/usr/local/smarthome/lib/network.py", line 292, in __init__
    self._id = f'({self.name if self.name else "HTTP"}_{self.baseurl})'
AttributeError: 'Http' object has no attribute 'name'
```

**Comment by Morg42** [comment]
Correct, `self.name` should have been `name`, missed it when introducing `self._id`...

Fixed
