### ISSUE TITLE
Error on restarting if shng is not running

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#498]
On Mac OS I (sometimes) get this error when i induce a smarthome.py -r and smarthome is not running:
```
> smarthome % bin/smarthome.py -r
A Process ID of 0 can not be killed, please kill SmartHomeNG manually
Stopping SmartHomeNG, please wait...
Traceback (most recent call last):
  File "bin/smarthome.py", line 218, in <module>
    lib.daemon.kill(PIDFILE, 30)
  File "/Users/ank/Documents/Github/smarthome/lib/daemon.py", line 206, in kill
    p.terminate()
  File "/Users/ank/Library/Python/3.8/lib/python/site-packages/psutil/__init__.py", line 278, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/ank/Library/Python/3.8/lib/python/site-packages/psutil/__init__.py", line 1236, in terminate
    self._send_signal(signal.SIGTERM)
  File "/Users/ank/Library/Python/3.8/lib/python/site-packages/psutil/__init__.py", line 1178, in _send_signal
    raise ValueError(
ValueError: preventing sending signal to process with PID 0 as it would affect every process in the process group of the calling process (os.getpid()) instead of PID 0
```

**Comment by msinn** [comment]
Should be fixed with commit https://github.com/smarthomeNG/smarthome/commit/231c542b85e7e6ce8e04a957ba28d6f0cd77cb62

**Comment by msinn** [comment]
SmartHomeNG v1.9.4 has been released
