### ISSUE TITLE
shpypi exception on version check of "pymodbus"

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#525]
Not sure if the issue is the "*" for vers_req_min an where it comes from..? However I sometimes get this exception what might be handled in a nicer way..?:
```
Jan 28 01:14:31 ERROR    lib.shpypi        lookup_pypi_releasedata: Package {'name': 'pymodbus', 'vers_installed': '3.1.1', 'is_required': False, 'is_required_for_plugins': True, 'is_required_for_testsuite': False, 'is_required_for_docbuild': False, 'required_group': '3', 'sort': '3pymodbus', 'vers_req_min': '*', 'vers_req_max': None, 'vers_req_msg': '', 'vers_req_source': '', 'vers_ok': False, 'vers_recent': False, 'pypi_version': '3.1.1', 'pypi_version_ok': True, 'pypi_version_not_available_msg': '', 'pypi_doc_url': 'https://pypi.org/pypi/pymodbus'} - Exception: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/shpypi.py", line 752, in lookup_pypi_releasedata
    self.check_package_version_data(package)
  File "/usr/local/smarthome/lib/shpypi.py", line 772, in check_package_version_data
    max_met = self._compare_versions(inst_vers, max, '<=')
  File "/usr/local/smarthome/lib/shpypi.py", line 1028, in _compare_versions
    v2 = self._version_to_list(vers2)
  File "/usr/local/smarthome/lib/shpypi.py", line 1052, in _version_to_list
    vsplit = vers.split('.')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by msinn** [comment]
To find out where it come from, i need the part of the file requirements/conf_all.txt which lists the needed pymodbus versions and the plugins which require them.

**Comment by onkelandy** [comment]
Weird enough I don't use any plugin that needs it - there is no entry in conf_all. The package is installed but I don't know exactly why, maybe because I wanted to provide it in the raspi image right away. 
I have python 3.9.2 on Debian.

**Comment by msinn** [comment]
Problem should be fixed with commit https://github.com/smarthomeNG/smarthome/commit/a8ea8f027f4ff005a3f57bf3ef86ca30683bdf8f

**Comment by msinn** [comment]
SmartHomeNG v1.9.4 has been released
