### ISSUE TITLE
Issue with smartdeviceplugin with UTF-8 response

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#563]
```
Jul 28 08:35:16 ERROR    lib.item.item     Item kino.oppo.control.power: problem running <bound method SmartDevicePlugin.update_item of <plugins.oppo.oppo object at 0x7f2c32be20>>: 'utf-8' codec can't decode byte 0xfd in position 4: invalid start byte
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/item/item.py", line 1808, in __update
    method(self, caller, source, dest)
  File "/usr/local/smarthome/lib/model/smartdeviceplugin.py", line 591, in update_item
    if not self.send_command(command, item(), custom=self._items_custom[item.id()]):
  File "/usr/local/smarthome/lib/model/smartdeviceplugin.py", line 673, in send_command
    result = self._send(data_dict)
  File "/usr/local/smarthome/plugins/oppo/__init__.py", line 80, in _send
    self._connection.send(data_dict)
  File "/usr/local/smarthome/lib/model/sdp/connection.py", line 149, in send
    response = self._send(data_dict)
  File "/usr/local/smarthome/lib/model/sdp/connection.py", line 745, in _send
    res = str(res, 'utf-8').strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 4: invalid start byte
```
Das passiert immer beim Ausschalten des Geräts. Die Antwort vom Gerät setzt sich normalerweise aus 
@<Antwort>Carriage Return
zusammen.

**Comment by Morg42** [comment]
resolved. Illegal characters are replaced using Python unicode error handlers. Further errors are excepted and logged, discarding the result.
