### ISSUE TITLE
Fehlermeldung im Backend

### ISSUE THREAD

**Issue by cstrassburg** [smarthomeNG/smarthome#68]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/smarthomeNG_master/plugins/backend/__init__.py", line 276, in index
    self.find_visu_plugin()
  File "/usr/local/smarthomeNG_master/plugins/backend/__init__.py", line 269, in find_visu_plugin
    self.logger.warning("Backend: visu plugin v{0} is too old to support BackendServer, please update".format(vers))
NameError: name 'vers' is not defined

**Comment by msinn** [comment]
Fixed

**Comment by msinn** [comment]
Why?

**Comment by cstrassburg** [comment]
getestet, läuft
