### ISSUE TITLE
SQLite Visu 2.8 Bugs (DB Upgrade and Item call)

### ISSUE THREAD

**Issue by ErKi1998** [smarthomeNG/smarthome#83]
Yesterday I started to install SmartHomeNG 1.2.435.dev completly new. Only the Database and the Items are copied from my old smarthome.py installation.

My first Error was: 
`2016-07-24 19:22:41 DEBUG    __init__     Main         SQLite 3.8.7.1 -- __init__.py:__init__:61
2016-07-24 19:22:45 DEBUG    __init__     Main         SQLite: database integrity ok -- __init__.py:__init__:78
2016-07-24 19:22:45 ERROR    plugin       Main         Plugin sql exception: No module named 'plugins.sqlite.upgrade' -- plugin.py:__init__:67
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/plugin.py", line 63, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance)
  File "/usr/local/smarthome/lib/plugin.py", line 108, in __init__
    exec("self.plugin.__init__(smarthome{0})".format(args))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthome/plugins/sqlite_visu2_8/__init__.py", line 93, in __init__
    import plugins.sqlite.upgrade
ImportError: No module named 'plugins.sqlite.upgrade'
`

I solved this Problem by changing the following lines in the __init__.py File:
Line 93 from `import plugins.sqlite.upgrade` to `import plugins.sqlite_visu2_8.upgrade`
Line 95 from `plugins.sqlite.upgrade.Upgrade(self._fdb, version)` to `plugins.sqlite_visu2_8.upgrade.Upgrade(self._fdb, version)`

After the successful Upgrade and a smarthomeNG restart (the first with the DB Upgrade worked (the Charts in smartVISU worked also) this Error occurs: 
`2016-07-24 22:12:01 DEBUG    __init__     Main         KNX[default]: Item EG.Eingang.temperature is mapped to KNX Instance default -- __init__.py:parse_item:253
2016-07-24 22:12:01 DEBUG    __init__     Main         KNX[default]: EG.Eingang.temperature listen on 5/0/3 -- __init__.py:parse_item:260
2016-07-24 22:12:01 DEBUG    __init__     Main         KNX[default]: EG.Eingang.temperature listen on and init with 5/0/3 -- __init__.py:parse_item:269
2016-07-24 22:12:01 ERROR    item         Main         Item EG.Eingang.temperature: problem creating: __call__() got an unexpected keyword argument 'last_change' -- item.py:__init__:221
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/item.py", line 219, in __init__
    child = Item(smarthome, self, child_path, value)
  File "/usr/local/smarthome/lib/item.py", line 276, in __init__
    update = plugin.parse_item(self)
  File "/usr/local/smarthome/plugins/sqlite_visu2_8/__init__.py", line 146, in parse_item
    item.set(value, 'SQLite', prev_change=prev_change, last_change=last_change)
TypeError: __call__() got an unexpected keyword argument 'last_change'`

I had found out that this error ist related to the positioning of my Items. Here an example:

Error:
[EG]
  [[Eingang]]
    [[[temperature]]]
      type = num
      sqlite = yes
      [[[[set]]]]
        type = num
        sqlite = yes
      [[[[state]]]]
        type = num
        sqlite = yes

No Error:
[EG]
  [[Eingang]]
    [[[Heizung]]]
      [[[[temperature]]]]
        type = num
        sqlite = yes
      [[[[set]]]]
        type = num
        sqlite = yes
      [[[[state]]]]
        type = num
        sqlite = yes

So somehowe the SQL Plugin doesn't work with Items which had child Objects with SQL.

Hopefully I could help you with my Explantation otherwise ask me in German.

**Comment by bmxp** [comment]
It's hard to read the above. Maybe it's easier if you include your code within <pre> and </pre>?

**Comment by ErKi1998** [comment]
Thanks for the tip.

Yes it's easier.

**Comment by ohinckel** [comment]
This was reported long time ago in https://github.com/mknx/smarthome/issues/141 and I also tried to find out what's the problem is. Maybe the bug was introduced again while changing the sqlite plugin back to some "older" version?

**Comment by ohinckel** [comment]
> 2016-07-24 19:22:45 ERROR    plugin       Main         Plugin sql exception: No module named 'plugins.sqlite.upgrade' -- plugin.py:__init__:67

Fixed - https://github.com/smarthomeNG/smarthome/commit/a2362c8982d3e5afc63195a18a4da408c4bddc36.

> SmartHomeNG 1.2.435.dev

At least the item class has the [set()](https://github.com/smarthomeNG/smarthome/blob/develop/lib/item.py#L468) method including the last_change keyword argument. So this should not happen with the develop version.

**Comment by i-am-offline** [comment]
The fix for this issue should be included in the "release-1.2" branch. I just ran into this issue while testing ...

**Comment by psilo909** [comment]
who merges to 1.2? i have to admit i am still too stupid to do that in github

**Comment by ohinckel** [comment]
Fix cherry-picked into `release-1.2`.

**Comment by ohinckel** [comment]
> So this should not happen with the develop version.

OK, just reviewed it and yes, the error still could happen :wink: The problem is not the two-level structure, the problem is the name of the sub-item which was set to `set`. So this will overwrite the `set()` method. I guess this will also happen when using other names of item`s methods.

So we should
a) ignore items with name matching some item`s methods and log an error or
b) refactor reading (item) configuration to handle the structure differently (not only put a key into a dict with a new dict)

I personally prefer the second approach, since it would strictly separate the structure from the data containers (years ago I was already wondering about this implementation, but I guess it was the easiest implementation).

What do the other's think?

**Comment by ohinckel** [comment]
Since I got no feedback for now, I started to implement a check on reserved worlds - for details see referenced PR.
