### ISSUE TITLE
Logging problems with Umlauts

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#85]
Hi there!

When I start smarthomeNG in debug mode I get the following problem (using the wetter.com plugin):

2016-07-30 18:50:41 DEBUG    item         env_loc      Item env.location.sunset = 2016-07-30 20:57:32.536098+02:00 via Logic None None -- item.py:**update:374
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/logging/__init**.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 95: ordinal not in range(128)
Call stack:
  File "/usr/local/lib/python3.4/threading.py", line 879, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/threading.py", line 859, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/smarthome/lib/scheduler.py", line 344, in _worker
    self._task(name, obj, by, source, dest, value)
  File "/usr/smarthome/lib/scheduler.py", line 354, in _task
    exec(obj.bytecode)
  File "/usr/smarthome/logics/wettercom.py", line 26, in <module>
    frame.text(forecast[date][2])
  File "/usr/smarthome/lib/item.py", line 287, in __call__
    self.__update(value, caller, source, dest)
  File "/usr/smarthome/lib/item.py", line 374, in __update
    self._change_logger("Item {} = {} via {} {} {}".format(self._path, value, caller, source, dest))
Message: 'Item wetter.vorhersage.heute.frueh.text = leicht bew\xf6lkt via Logic None None'
Arguments: ()

As it is a "logging error" I guess it's not part of the plugin.. How can I avoid the error? Thanks!!!

**Comment by onkelandy** [comment]
One more weird logging phenomenon... Sometimes the time stamps or log entry order get messed up when restarting SmarthomeNG. This actually really only happens on restarts is no big deal, but nevertheless quite weird..

2016-08-03  21:59:53 WARNING  Main         Client 10.0.0.83:61631 requested invalid item: licht.eg.bad.spots.sperren
2016-08-03  21:59:53 WARNING  Main         Client 10.0.0.83:61631 requested invalid item: licht.eg.gang.sperren
2016-08-03  22:11:22 WARNING  Main         Client 10.0.0.27:64410 requested invalid item: licht.eg.bad.spots.sperren
2016-08-03  22:11:22 WARNING  Main         Client 10.0.0.27:64410 requested invalid item: licht.eg.gang.sperren
2016-08-03  21:11:01 WARNING  Main         --------------------   Init SmartHomeNG 1.1.448.dev   --------------------
2016-08-03  23:12:30 WARNING  Main         Client 10.0.0.27:58735 requested invalid item: licht.eg.bad.spots.sperren
2016-08-03  23:12:30 WARNING  Main         Client 10.0.0.27:58735 requested invalid item: licht.eg.gang.sperren
2016-08-03  21:22:01 WARNING  Main         --------------------   Init SmartHomeNG 1.1.448.dev   --------------------

**Comment by msinn** [comment]
The log entry order is not messed up. The Init-message gives the time in gmt and not in local time. I push a fix for that on the weekend. 

But: This has nothing to do with your umlaut problem.

**Comment by onkelandy** [comment]
Both true ;) Actually I've changed my entry as it got obvious that the UCT time is the problem.. But anyhow I'll create a new issue with the correct "problem description" ;)

**Comment by psilo909** [comment]
die logger.infos gehen bei mir einwandfrei mit Umlauten. Hast Du bei Dir mal probiert, einfach ein logger.info('äüö') in die Logik zu schreiben? ich hatte den issue mit wetter.com noch nie, daher etwas seltsam..

**Comment by onkelandy** [comment]
Das Problem besteht nur, wenn ich im Debug-Modus starte, also smarthome.py --debug
Ansonsten auch nicht.

**Comment by psilo909** [comment]
ich bin mit -d im debug modus und es geht, könnte mglw was mti deinem system zu tun haben?

**Comment by onkelandy** [comment]
Hm, es ist also in der Tat so, dass im Daemon-Modus alles problemlos funzt - habe gerade eine Logik wie von dir geschrieben getriggert. äöü. Aber im Debug Modus kommt dann der Fehler. 

Mit raspi-config habe ich de.UTF-8 als Locale eingerichtet. Wenn ich locale aufrufe, erhalte ich allerdings immer ein POSIX bei allen einträgen.

Hab jetzt mal manuell die entsprechenden Variablen gesetzt, 
export LC_ALL=de_DE.utf8
export LANGUAGE=de_DE.utf8

Und siehe da - kein Problem mehr!! Danke für den Hinweis. Kurze Frage noch, hast du die zwei obigen Befehle bei dir im /etc/profile drin?

**Comment by psilo909** [comment]
@onkelandy auf meiner Synology mit DSM 6 stehen die hier drin:

export LC_ALL=en_US.utf8
export LANG=en_US.utf8
